packages:
  - packages/*
  - packages/adapters/*
  - packages/plugins/*
  - packages/plugins/examples/*
  - packages/editor
  - packages/editor/*
  - packages/editor/udecode/*
  - server
  - server-nest
  - client
  - cli
